# Core design tokens - minimal overrides for hardcoded OOXML templates

fonts:
  primary: "Liberation Sans"
  fallback: "Arial"

colors:
  text: "#000000" 
  accent: "#18a303"    # LibreOffice green
  bg: "#ffffff"

grid:
  line_height: 17      # twentieths of a point
  font_size: 24        # half-points (12pt)