name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'website/**'
      - 'docusaurus/**'
      - 'docs/**/*.md'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: ./docusaurus
        run: npm install
      
      - name: Build Docusaurus
        working-directory: ./docusaurus
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Prepare combined site
        run: |
          # Copy main website
          mkdir -p _site
          cp -r website/* _site/
          # Copy Docusaurus build to docs subdirectory
          mkdir -p _site/docs
          cp -r docusaurus/build/* _site/docs/
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          enablement: true
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4